/*
 * FrmPrimaveraSelectProject.java
 *
 * Created on 07 Ekim 2008 Salı, 16:00
 */

package saprim;

import com.primavera.integration.client.bo.object.*;
import saprim.primavera.*;
import javax.swing.tree.*;

/**
 *
 * @author  Kerem
 */
public class FrmPrimaveraSelectProject extends javax.swing.JFrame {

    public enum TARGET_OBJECT { EPS, PROJECT };
    
    private saprim.integration.integrator integ;
    private EPS[] epss;
    private Project[] projects;
    private DefaultMutableTreeNode treeRoot;
    private TARGET_OBJECT targetObject;
    
    /** Creates new form FrmPrimaveraSelectProject */
    public FrmPrimaveraSelectProject(saprim.integration.integrator I, TARGET_OBJECT T) {
        initComponents();
        
        targetObject = T;
        integ = I;
        btnNext.setEnabled(false);
        
        if (targetObject == TARGET_OBJECT.EPS)
        {
            lblSelection.setText("Please select an EPS");
        }
        else if (targetObject == TARGET_OBJECT.PROJECT)
        {
            lblSelection.setText("Please select a project");
        }
        
        try
        {
            epss = Main.primavera.getEPSList();
            projects = Main.primavera.getProjectList();
            treeRoot = new DefaultMutableTreeNode("EPS");
            fillTree(null, treeRoot);
            treeProj.setModel(new DefaultTreeModel(treeRoot));
        }
        catch(Exception ex)
        {
            ex.printStackTrace();
            this.dispose();
            return;            
        }
        
        btnNext.setEnabled(true);
    }
    
    private void fillTree(com.primavera.common.value.ObjectId Parent, DefaultMutableTreeNode Node) throws Exception
    {   
        for (int n = 0; n < epss.length; n++)
        {
            if ( 
                 (epss[n].getParentObjectId() == null && Parent == null)
                    ||
                 (epss[n].getParentObjectId() != null && epss[n].getParentObjectId().equals(Parent))
               )
            {
                DefaultMutableTreeNode tn = new DefaultMutableTreeNode(new EPSTreeWrapper(epss[n]), true);
                fillTree(epss[n].getObjectId(), tn);
                
                if (targetObject == TARGET_OBJECT.PROJECT)
                {
                    for (int m = 0; m < projects.length; m++)
                    {
                        if (projects[m].getParentEPSObjectId().equals(epss[n].getObjectId()))
                        {
                            DefaultMutableTreeNode tp = new DefaultMutableTreeNode(new ProjectTreeWrapper(projects[m]), false);
                            tn.add(tp);
                        }
                    }
                }
                
                Node.add(tn);
            }
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        treeProj = new javax.swing.JTree();
        lblSelection = new javax.swing.JLabel();
        btnNext = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/saprim/prilogo.PNG"))); // NOI18N

        jScrollPane1.setViewportView(treeProj);

        lblSelection.setText("Please select a project:");

        btnNext.setText("Next");
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                    .addComponent(jLabel2)
                    .addComponent(btnNext, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblSelection, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(lblSelection)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(btnNext)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed

    int[] s = treeProj.getSelectionRows();
    if (s.length != 1) return;
    
    try
    {   
        if (targetObject == TARGET_OBJECT.PROJECT)
        {
            ProjectTreeWrapper ptw = (ProjectTreeWrapper) ((DefaultMutableTreeNode)treeProj.getSelectionModel().getSelectionPaths()[0].getLastPathComponent()).getUserObject();
            integ.setPrimaveraProjectSelected(ptw.getProject());
            this.dispose();
        }
        else if(targetObject == TARGET_OBJECT.EPS)
        {
            EPSTreeWrapper etw = (EPSTreeWrapper) ((DefaultMutableTreeNode)treeProj.getSelectionModel().getSelectionPaths()[0].getLastPathComponent()).getUserObject();
            integ.setPrimaveraEPSSelected(etw.getEPS());
            this.dispose();
        }
    }
    catch(Exception ex) 
    { 
        ex.printStackTrace();
        return;
    }
    
}//GEN-LAST:event_btnNextActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmPrimaveraSelectProject(null, null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNext;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblSelection;
    private javax.swing.JTree treeProj;
    // End of variables declaration//GEN-END:variables

}
