/*
 * FrmSapSelectProject.java
 *
 * Created on 17 Eylül 2008 Çarşamba, 16:49
 */

package saprim;

/**
 *
 * @author  Kerem
 */
public class FrmSapSelectProject extends javax.swing.JFrame {
    
    private saprim.integration.integrator integ;
    private saprim.integration.Project[] projects;
    
    /** Creates new form FrmSapSelectProject */
    public FrmSapSelectProject(saprim.integration.integrator I, boolean ShowNewProjectCheckbox) {
        initComponents();
        integ = I;
        
        btnNext.setEnabled(false);
        
        try
        {
            projects = Main.sap.getProjectList(ShowNewProjectCheckbox);
            lstProject.setListData(projects);
        }
        catch(Exception ex)
        {
            ex.printStackTrace();
            this.dispose();
            return;
        }
        
        chkNew.setVisible(ShowNewProjectCheckbox);
        btnNext.setEnabled(true);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstProject = new javax.swing.JList();
        jLabel2 = new javax.swing.JLabel();
        btnNext = new javax.swing.JButton();
        chkNew = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/saprim/saplogo2.png"))); // NOI18N

        lstProject.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(lstProject);

        jLabel2.setText("Please select a project:");

        btnNext.setText("Next");
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });

        chkNew.setText("Create New Project");
        chkNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkNewActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(chkNew, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(btnNext))
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNext)
                    .addComponent(chkNew))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        
        if (lstProject.getSelectedIndex() < 0 && !chkNew.isSelected()) return;
        
        btnNext.setEnabled(false);
        integ.setSapProjectSelected(chkNew.isSelected() ? null : projects[lstProject.getSelectedIndex()], chkNew.isVisible() && chkNew.isSelected());
        this.dispose();
    }//GEN-LAST:event_btnNextActionPerformed

private void chkNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkNewActionPerformed
    lstProject.setEnabled(!chkNew.isSelected());
}//GEN-LAST:event_chkNewActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmSapSelectProject(null, false).setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNext;
    private javax.swing.JCheckBox chkNew;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList lstProject;
    // End of variables declaration//GEN-END:variables
    
}
